### ISSUE TITLE
DevOps onboarding tracking issue

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/onken-web#5]
I'm going to be working on several changes to this repository to bring it in line with standards for RoboJackets as well as the Onken project. Feel free to discuss in issue comments, this list can change.

- [x] Rename to `onken-web` to comply with RoboJackets repository naming conventions and allow for other frontends in the future (unlikely?)
- [x] Change the repository description to something, haven't decided yet
- [x] Set up CircleCI to ensure code builds for production on every push
- [x] Set up a style checker (@Holben888)
  - I like [Hound](https://houndci.com/) for the backend project, [Stickler](https://stickler-ci.com/) also works. Pick one and configure it as you wish.
- [x] Set up deployment tooling to run the application in the staging environment
- [x] Bring over labels from the backend repo
- [x] Set up GitHub notifications into SCC Slack
- [ ] Set up Code Climate for static analysis
- [ ] Set up LGTM for static analysis
